export const ActionTypes = {
    GET_CLUBS : "GET_CLUBS",
    GET_CLUB : "GET_CLUB",
    UPDATE_CLUB: "UPDATE-CLUB",
    ERROR_UPDATE_CLUB : "ERROR_UPDATE_CLUB",
    CREATE_CLUB: "CREATE_CLUB",
    DELETE_CLUB: "DELETE_CLUB",
    ERROR_DELETE_CLUB: "ERROR_DELETE_CLUB",

    GET_TEAMS : "GET_TEAMS",
    GET_TEAMS_WITH_QUERY:"GET_TEAMS_WITH_QUERY",
    DELETE_TEAM : "DELETE_TEAM",
    CREATE_TEAM:"CREATE_TEAM",
    GET_TEAM : "GET_TEAM",
    UPDATE_TEAM: "UPDATE_TEAM",

    GET_ALERT: "GET_ALERT",
    STOP_ALERT: "STOP_ALERT",
    
    GET_SPORTS : "GET_SPORTS",
    DELETE_SPORT: "DELETE_SPORT",

    GET_FIXTURES: "GET_FIXTURES",
    DELETE_FIXTURE: "DELETE_FIXTURE",
    ERROR_DELETE_FIXTURE: "ERROR_DELETE_FIXTURE",
    CREATE_FIXTURE: "CREATE_FIXTURE",
    ERROR_CREATE_FIXTURE:"ERROR_CREATE_FIXTURE",
    GET_FIXTURE : "GET_FIXTURE",
    UPDATE_FIXTURE: "UPDATE_FIXTURE",
    ERROR_UPDATE_FIXTURE:"ERROR_UPDATE_FIXTURE",

    GET_FIXTURE_RESULTS: "GET_FIXTURE_RESULTS",
    CREATE_FIXTURE_RESULT:"UPDATE_FIXTURE_RESULT",
    ERROR_CREATE_FIXTURE_RESULT:"ERROR_UPDATE_FIXTURE_RESULT"

    

    
}